remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: TilStat
description: Unofficial stats for TIL exam at PoliTO


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      remote_theme: pages-themes/cayman@v0.2.0
      plugins:
      - jekyll-remote-theme # add this line to the plugins list if you already have one
      title: TilStat
      description: Unofficial stats for TIL exam at PoliTO      
